In [1]:
import pandas as pd
import numpy as np

matches = pd.read_csv('data/matches.csv')
matches.head(15)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba
10,335992,2007/08,Bangalore,2008-04-26,League,SR Watson,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,136.0,20.0,N,NaN,MR Benson,IL Howell
11,335993,2007/08,Chennai,2008-04-26,League,JDP Oram,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,148.0,20.0,N,NaN,BF Bowden,AV Jayaprakash
12,335994,2007/08,Mumbai,2008-04-27,League,AC Gilchrist,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,155.0,20.0,N,NaN,Asad Rauf,SL Shastri
13,335995,2007/08,Chandigarh,2008-04-27,League,SM Katich,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,bat,Kings XI Punjab,wickets,4.0,159.0,20.0,N,NaN,RE Koertzen,I Shivram
14,335996,2007/08,Bangalore,2008-04-28,League,MS Dhoni,M Chinnaswamy Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,179.0,20.0,N,NaN,BR Doctrove,RB Tiffin

In [2]:
print(matches.columns)

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [3]:
df = matches[['team1', 'team2', 'venue', 'toss_winner', 'toss_decision', 'winner']]
df = df.dropna()
print(df.shape)
df.head()

(1090, 6)

,team1,team2,venue,toss_winner,toss_decision,winner
0,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,Chennai Super Kings
2,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,Delhi Daredevils
3,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,Kolkata Knight Riders

In [6]:
#Encoding - before data cleaning, to see what needs to be corrected

from sklearn.preprocessing import LabelEncoder

# Encode toss_decision
le = LabelEncoder()
df['toss_decision'] = le.fit_transform(df['toss_decision'])

# Encode winner (target)
df['winner_encoded'] = le.fit_transform(df['winner'])

# One Hot Encode the rest
df_encoded = pd.get_dummies(df, columns=['team1', 'team2', 'venue', 'toss_winner'])

print(df_encoded.shape)
df_encoded.head()

(1090, 118)

,toss_decision,winner,winner_encoded,team1_Chennai Super Kings,team1_Deccan Chargers,team1_Delhi Capitals,team1_Delhi Daredevils,team1_Gujarat Lions,team1_Gujarat Titans,team1_Kings XI Punjab,...,toss_winner_Lucknow Super Giants,toss_winner_Mumbai Indians,toss_winner_Pune Warriors,toss_winner_Punjab Kings,toss_winner_Rajasthan Royals,toss_winner_Rising Pune Supergiant,toss_winner_Rising Pune Supergiants,toss_winner_Royal Challengers Bangalore,toss_winner_Royal Challengers Bengaluru,toss_winner_Sunrisers Hyderabad
0,1,Kolkata Knight Riders,8,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0,Chennai Super Kings,0,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,0,Delhi Daredevils,3,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,0,Royal Challengers Bangalore,16,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,0,Kolkata Knight Riders,8,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
#which team got assigned with which number?

le_winner = LabelEncoder()
le_winner.fit(df['winner'])
for i, team in enumerate(le_winner.classes_):
    print(i, team)

0 Chennai Super Kings
1 Deccan Chargers
2 Delhi Capitals
3 Delhi Daredevils
4 Gujarat Lions
5 Gujarat Titans
6 Kings XI Punjab
7 Kochi Tuskers Kerala
8 Kolkata Knight Riders
9 Lucknow Super Giants
10 Mumbai Indians
11 Pune Warriors
12 Punjab Kings
13 Rajasthan Royals
14 Rising Pune Supergiant
15 Rising Pune Supergiants
16 Royal Challengers Bangalore
17 Royal Challengers Bengaluru
18 Sunrisers Hyderabad

In [11]:
#data cleaning - standardizing team names

df['team1'] = df['team1'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Kings XI Punjab': 'Punjab Kings'
})

df['team2'] = df['team2'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Kings XI Punjab': 'Punjab Kings'
})

df['toss_winner'] = df['toss_winner'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Kings XI Punjab': 'Punjab Kings'
})

df['winner'] = df['winner'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Kings XI Punjab': 'Punjab Kings'
})

In [17]:
#again - which team got assigned with which number?

le_winner = LabelEncoder()
le_winner.fit(df['winner'])
for i, team in enumerate(le_winner.classes_):
    print(i, team)

0 Chennai Super Kings
1 Deccan Chargers
2 Delhi Capitals
3 Gujarat Lions
4 Gujarat Titans
5 Kochi Tuskers Kerala
6 Kolkata Knight Riders
7 Lucknow Super Giants
8 Mumbai Indians
9 Pune Warriors
10 Punjab Kings
11 Rajasthan Royals
12 Rising Pune Supergiants
13 Royal Challengers Bengaluru
14 Sunrisers Hyderabad

In [27]:
#printing unique venues just to be sure, there aren't any duplicates

print(sorted(df['venue'].unique()))

['Arun Jaitley Stadium', 'Barabati Stadium', 'Barsapara Cricket Stadium, Guwahati', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow', 'Brabourne Stadium', 'Buffalo Park', 'De Beers Diamond Oval', 'Dr DY Patil Sports Academy', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Dubai International Cricket Stadium', 'Eden Gardens', 'Feroz Shah Kotla', 'Green Park', 'Himachal Pradesh Cricket Association Stadium, Dharamsala', 'Holkar Cricket Stadium', 'JSCA International Stadium Complex', 'Kingsmead', 'M Chinnaswamy Stadium', 'MA Chidambaram Stadium', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'Maharashtra Cricket Association Stadium, Pune', 'Narendra Modi Stadium, Ahmedabad', 'Nehru Stadium', 'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval', 'Punjab Cricket Association IS Bindra Stadium', 'Rajiv Gandhi International Stadium', 'Sardar Patel Stadium, Motera', 'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Shaheed Veer Narayan Singh International Stadium', 'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium', "St George's Park", 'Subrata Roy Sahara Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Wankhede Stadium', 'Zayed Cricket Stadium, Abu Dhabi']

In [38]:
#manually listing the duplicate venue

df['venue'] = df['venue'].replace({
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',
    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
    'Eden Gardens, Kolkata': 'Eden Gardens',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali': 'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh': 'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association Stadium, Mohali': 'Punjab Cricket Association IS Bindra Stadium',
    'Rajiv Gandhi International Stadium, Uppal': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',
    'Sawai Mansingh Stadium, Jaipur': 'Sawai Mansingh Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',
    'Himachal Pradesh Cricket Association Stadium, Dharamsala': 'Himachal Pradesh Cricket Association Stadium',
    'Maharashtra Cricket Association Stadium, Pune': 'Maharashtra Cricket Association Stadium',
    'Zayed Cricket Stadium, Abu Dhabi': 'Zayed Cricket Stadium',
    'Barsapara Cricket Stadium, Guwahati': 'Barsapara Cricket Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur': 'Maharaja Yadavindra Singh International Cricket Stadium',
    'Vidarbha Cricket Association Stadium, Jamtha': 'Vidarbha Cricket Association Stadium',
    'Narendra Modi Stadium, Ahmedabad': 'Narendra Modi Stadium',
    'Sardar Patel Stadium, Motera': 'Sardar Patel Stadium',
    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
})

In [39]:
print(sorted(df['venue'].unique()))
print('\n', df['team1'].unique())
print('\n', df['team2'].unique())
print('\n', df['toss_winner'].unique())
print('\n', df['winner'].unique())

['Arun Jaitley Stadium', 'Barabati Stadium', 'Barsapara Cricket Stadium', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'Brabourne Stadium', 'Buffalo Park', 'De Beers Diamond Oval', 'Dr DY Patil Sports Academy', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Dubai International Cricket Stadium', 'Eden Gardens', 'Feroz Shah Kotla', 'Green Park', 'Himachal Pradesh Cricket Association Stadium', 'Holkar Cricket Stadium', 'JSCA International Stadium Complex', 'Kingsmead', 'M Chinnaswamy Stadium', 'MA Chidambaram Stadium', 'Maharaja Yadavindra Singh International Cricket Stadium', 'Maharashtra Cricket Association Stadium', 'Narendra Modi Stadium', 'Nehru Stadium', 'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval', 'Punjab Cricket Association IS Bindra Stadium', 'Rajiv Gandhi International Stadium', 'Sardar Patel Stadium', 'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Shaheed Veer Narayan Singh International Stadium', 'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium', "St George's Park", 'Subrata Roy Sahara Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium', 'Wankhede Stadium', 'Zayed Cricket Stadium']

 ['Royal Challengers Bengaluru' 'Punjab Kings' 'Delhi Capitals'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Lucknow Super Giants' 'Gujarat Titans']

 ['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bengaluru' 'Deccan Chargers' 'Punjab Kings'
 'Delhi Capitals' 'Mumbai Indians' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Gujarat Titans' 'Lucknow Super Giants']

 ['Royal Challengers Bengaluru' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Punjab Kings' 'Kolkata Knight Riders'
 'Delhi Capitals' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Gujarat Lions' 'Rising Pune Supergiants'
 'Gujarat Titans' 'Lucknow Super Giants']

 ['Kolkata Knight Riders' 'Chennai Super Kings' 'Delhi Capitals'
 'Royal Challengers Bengaluru' 'Rajasthan Royals' 'Punjab Kings'
 'Deccan Chargers' 'Mumbai Indians' 'Pune Warriors' 'Kochi Tuskers Kerala'
 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Gujarat Titans' 'Lucknow Super Giants']

In [40]:
#Encoding - after data cleaning

from sklearn.preprocessing import LabelEncoder

# Encode toss_decision
le = LabelEncoder()
df['toss_decision'] = le.fit_transform(df['toss_decision'])

# Encode winner (target)
df['winner_encoded'] = le.fit_transform(df['winner'])

# One Hot Encode the rest
df_encoded = pd.get_dummies(df, columns=['team1', 'team2', 'venue', 'toss_winner'])

print(df_encoded.shape)
df_encoded.head()

(1090, 88)

,toss_decision,winner,winner_encoded,team1_Chennai Super Kings,team1_Deccan Chargers,team1_Delhi Capitals,team1_Gujarat Lions,team1_Gujarat Titans,team1_Kochi Tuskers Kerala,team1_Kolkata Knight Riders,...,toss_winner_Kochi Tuskers Kerala,toss_winner_Kolkata Knight Riders,toss_winner_Lucknow Super Giants,toss_winner_Mumbai Indians,toss_winner_Pune Warriors,toss_winner_Punjab Kings,toss_winner_Rajasthan Royals,toss_winner_Rising Pune Supergiants,toss_winner_Royal Challengers Bengaluru,toss_winner_Sunrisers Hyderabad
0,1,Kolkata Knight Riders,6,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,0,Chennai Super Kings,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0,Delhi Capitals,2,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,0,Royal Challengers Bengaluru,13,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,0,Kolkata Knight Riders,6,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [41]:
#define x and y

X = df_encoded.drop(columns=['winner', 'winner_encoded'])
y = df_encoded['winner_encoded']

print(X.shape)
print(y.shape)

(1090, 86)
(1090,)

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (872, 86)
X_test: (218, 86)